version: "2.2"

services:
  core:
    build: src/
    restart: always
    environment:
      BOT_NICKNAME: "Bot"
      UTOPIA_HOST: "enticer-utopia-api"
      UTOPIA_TOKEN: "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
      UTOPIA_PORT: "22825"
      UTOPIA_WS_PORT: "25000"
      ACTION_TIMEOUT_HOURS: "6"
      DEBUG_IMMEDIATELY_START: "true"
      CHAT_IDS: "E36921F241EA9A3ABE03308BF41E0C37:7059882759A545496050909C910D8AA0,EB3D3060924FE529271B2511DF51071F;EF978A706EEE71AB24A29D069CCCAA7D:7059882759A545496050909C910D8AA0"
      AD_MESSAGE1: "What about interesting channels? See"
      AD_MESSAGES: "1"
    depends_on:
      - utopia-api
      - db
    networks:
      - unetwork
    stdin_open: true
    tty: true

  utopia-api:
    image: uto9234/utopia-api
    hostname: enticer-utopia-api
    restart: always
    ports:
      - 22825:22825
    environment:
      XDG_RUNTIME_DIR: /tmp/runtime-root
    networks:
      - unetwork
    volumes:
      - type: bind
        source: ./account.db
        target: /app/account.db
    logging:
      driver: "local"
      options:
        max-size: "5m"
        max-file: "5"

networks:
  unetwork:
    driver: bridge
